---
- name:       Determine if SSL certificate directory exist,If not, then set up directory.
  file:       path={{ generate_certification_path }} state=directory
  when:       inventory_hostname == "{{ groups['masters'][0] }}"
  # 也可以替換成以下方法
  # delegate_to: "{{ groups['masters'][0] }}"
  # run_once: true
  register:   ssl_directory

# - name:     set up  SSL certificate directory
#   when:     not ssl_directory.stat.exists
#   file:     path={{ generate_certification_path }} state=directory
#   delegate_to: "{{ groups['masters'][0] }}"
#   run_once: true
#   register: ssl_directory

- name:       Determine if SSL CA config exist.
  stat:       path={{ ca_config_path }}
  when:       inventory_hostname == "{{ groups['masters'][0] }}"
  # 也可以替換成以下方法
  # delegate_to: "{{ groups['masters'][0] }}"
  # run_once: true
  register:   ca_config

- name:       If not, then set up SSL CA config.
  when:       not ca_config.stat.exists
  template:
    src:      ca-config.json.j2
    dest:     "{{ ca_config_path }}"
    owner:    root
    group:    root
    mode:     '0600'
  when:       inventory_hostname == "{{ groups['masters'][0] }}"
  # 也可以替換成以下方法
  # delegate_to: "{{ groups['masters'][0] }}"
  # run_once: true
  register:   gen_ca_config

- name:       Determine if SSL certificate config exist
  stat:       path={{ ca_csr_path }}
  ############################## Todo fix it later
  when:       inventory_hostname == "{{ groups['masters'][0] }}"
  # 也可以替換成以下方法
  # delegate_to: "{{ groups['masters'][0] }}"
  # run_once: true
  register:   csr_config

- name:       If not, then set up SSL certificate config
  when:       csr_config.stat.exists
  template:
    src:      ca-csr.json.j2
    dest:     "{{ generate_certification_path }}/{{ item.file }}"
    owner:    root
    group:    root
    mode:     '0600'
  with_items:
    - { file: ca-csr.json,                 name: kubernetes, org: Kubernetes }
  ############################## Todo fix it later
  when:       inventory_hostname == "{{ groups['masters'][0] }}"

  # 也可以替換成以下方法
  # delegate_to: "{{ groups['masters'][0] }}"
  # run_once: true
  register:   gen_csr_config
