---
- name:         Determine if kubctl binaries installation exist.
  stat:
    path:       "{{ bin }}/{{ packages.kubectl.name }}"
  changed_when: false
  register:     kubectl_bin

- name:         If not, then set up kubectl.
  when:         not kubectl_bin.stat.exists
  block:
    - name:   Download kubctl binaries.
      get_url:
        url:  "{{ packages.kubectl.url }}"
        dest: "{{ download }}/{{ packages.kubectl.name }}"
        mode: 0755

    - name:   Copy kubectl to {{ bin }}.
      copy:
        src:  "{{ download }}/{{ packages.kubectl.name }}"
        dest: "{{ bin }}"
        mode: 0755
        remote_src: True

  always:
    - name:     Clean temporary files.
      file:
        path:   "{{ download }}/{{ packages.kubectl.name }}"
        state:  absent
