---
- name:        Copy ca pki frome deploy node
  copy:
    src:       "{{ certification.local_ssl }}/{{ item[0] }}/{{ item[0] }}{{ item[1] }}"
    dest:      "{{ kubernetes.pki }}/{{ item[0] }}{{ item[1] }}"
  with_nested:
    - " ca "
    - [-ca.pem,-ca-config.json, -ca.csr, -ca-key.pem,-client.csr, -client-key.pem, -client.pem]

- name:        Copy kubernetes client pki frome deploy node
  copy:
    src:       "{{ certification.local_ssl }}/{{ item[0] }}/{{ item[0] }}{{ item[1] }}"
    dest:      "{{ kubernetes.pki }}/{{ item[0] }}{{ item[1] }}"
  with_nested:
    - "{{ fetch_ca }}"
    - [-client.csr, -client-key.pem, -client.pem]

- name:        Copy token.csv frome deploy node
  copy:
    src:       "{{ certification.local_ssl }}/token.csv"
    dest:      "{{ kubernetes.dir }}/token.csv"
