---
- name:        Set up Kubernetes dir.
  file:
    path:      "{{ kubernetes.dir }}"
    state:     directory

- name:        Set up Kubernetes pki dir.
  file:
    path:      "{{ kubernetes.pki }}"
    state:     directory

- include: copy.yaml

- include: setup.yaml
