---

- name:       Determine if etc directory exist,If not, then set up directory.
  file:
    path:     "{{ directory }}"
    state:    directory

- name:       Determine if etc SSL directory exist,If not, then set up directory.
  file:
    path:     "{{ directory_ssl }}"
    state:    directory

- name:       Copy Etcd certificate from deploy node
  copy:
    src:      "{{ certification.local_ssl }}/{{ certification.etcd.name }}/{{ item }}"
    dest:     "{{ directory_ssl }}/{{ item }}"
  with_items:
    - "{{ etcd_ssl }}"

- name:     Copy Etcd conf template file
  template:
    src:    etcd.conf.j2
    dest:   "{{ directory }}/etcd.conf"
