---
- name:       Determine if etcd exist.
  stat:
    path:   "{{ opt }}/{{ item.file }}"
  register: tmp_etcd
  with_items:
    - "{{ packages.etcd }}"

- name:     If not,then Download etcd.
  get_url:
    url:    "{{ item.1.url }}/{{ item.1.file }}{{ item.1.format}}"
    dest:   "{{ download }}/{{ packages.etcd.file }}"
  when:     not tmp_etcd.results[item.0].stat.exists
  with_indexed_items:
    - "{{ packages.etcd }}"
  register: down

- name:     Unarchive etcd.
  unarchive:
    src:    "{{ download }}/{{ item.1.file }}"
    dest:   "{{ opt }}"
    copy:   no
  when:     down.results[item.0].changed == true
  with_indexed_items:
    - "{{ packages.etcd }}"
  register: etcd_unarchived

- name:     Clean temporary files.
  file:
    path:   "{{ download }}/{{ item.file }}"
    state:  absent
  with_items:
    - "{{ packages.etcd }}"

- name:     Symlinks etcd
  file:
    src:    "{{ opt }}/{{ packages.etcd.file }}/{{ item }}"
    dest:   "{{ bin }}/{{ item }}"
    state:  link
    force:  yes
  with_items:
  - "{{ packages.etcd.archive.file }}"

- name:     Etcd configuration
  include:  config.yaml

- name:     Add Etcd systemd service
  include:  systemd.yaml
