---

- name:            Determine if etcd data directory exist,If not, then set up directory.
  file:
    path:          "{{ directory_data }}"
    state:         directory
#
#   debug:
#     msg:
- name:            Copy etcd systemd service frome deploy node
  template:
    src:           etcd.service.j2
    dest:          "{{ directory_systemd }}/etcd.service"

- name:            Enable and restart etcd
  systemd:
    name:          etcd
    daemon_reload: yes
    state:         restarted
    enabled:       yes
