FROM ubuntu:16.04
MAINTAINER jason<jason.meng.lee@gmail.com>

RUN apt-get update && \
    apt-get install linux-headers-$(uname -r) && \
    apt-get install --no-install-recommends --no-install-suggests -y keepalived && \
    rm -rf /var/lib/apt/lists/*

COPY config /etc/keepalived/
COPY entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]