---
etcd_group:                       etcds
etcd_client_port:                 2379
etcd_peer_port:                   2380
etcd_ip_addr:                     "{% if etcd_interface != '' %}{{ hostvars[inventory_hostname]['ansible_' + etcd_interface].ipv4.address }}
{%- else %}{{ hostvars[inventory_hostname].ansible_default_ipv4.address }}{% endif %}"
etcd_listen_peer_urls:            "https://0.0.0.0:{{ etcd_peer_port }}"
etcd_advertise_client_urls:       "https://{{ etcd_ip_addr }}:{{ etcd_client_port }}"
etcd_listen_client_urls:          "https://0.0.0.0:{{ etcd_client_port }}"
etcd_initial_advertise_peer_urls: "https://{{ etcd_ip_addr }}:{{ etcd_peer_port }}"

packages:
  etcd:
    name:                         etcd
    url:                          "{{ source.etcd.url }}/{{ source.etcd.version }}"
    file:                         "etcd-{{ source.etcd.version }}-linux-amd64"
    format:                       ".tar.gz"
    archive:
      file:
        - "etcd"
        - "etcdctl"

directory:                        /etc/etcd
directory_ssl:                    /etc/etcd/ssl
directory_data:                   /var/lib/etcd
directory_systemd:                /etc/systemd/system
directory_wal_dir:                /var/lib/etcd/wal

snapshot_count:                   100
heartbeat_interval:               100
election_timeout:                 1000

auto_tls:                         true
peer_auto_tls:                    true
client_cert_auth:                 true
peer_client_cert_auth:            true
max_snapshots:                    5
max_wals:                         5

etcd_ssl:
  - "etcd-ca.pem"
  - "etcd-client-key.pem"
  - "etcd-client.pem"
  - "etcd-ca-key.pem"
  - "etcd-client.csr"
  - "etcd-ca.csr"

etcd_ca:                               "{{ directory_ssl }}/etcd-ca.pem"
etcd_cert:                             "{{ directory_ssl }}/etcd-client.pem"
etcd_cert_key:                         "{{ directory_ssl }}/etcd-client-key.pem"


initial_cluster_state:            new
initial_cluster_token:            etcd-cluster
