---
- name:               Determine if CA tools exist.
  stat:
    path:             "{{ opt }}/{{ item.name }}"
  register:           tmp_ca_tool
  delegate_to:        "{{ groups['masters'][0] }}"
  run_once:           true
  with_items:
  - "{{ packages.cfssl }}"
  - "{{ packages.cfssljson }}"

- name:               Download CA tools to {{ download }}.
  get_url:
    url:              "{{ item.1.url }}/{{ item.1.file }}"
    dest:             "{{ download }}/{{ item.1.file }}"
  when:               not tmp_ca_tool.results[item.0].stat.exists
  delegate_to:        "{{ groups['masters'][0] }}"
  run_once:           true
  with_indexed_items:
  - "{{ packages.cfssl }}"
  - "{{ packages.cfssljson }}"
  register:           ca_tool_down

- name:               copy CA tools to {{ opt }}.
  when:               ca_tool_down.results[item.0].changed ==true
  copy:
    src:              "{{ download }}/{{  item.1.file }}"
    dest:             "{{ opt }}/{{ item.1.name }}"
    owner:            root
    group:            root
    mode:             0755
    remote_src:       True
  delegate_to:        "{{ groups['masters'][0] }}"
  run_once:           true
  with_indexed_items:
  - "{{ packages.cfssl }}"
  - "{{ packages.cfssljson }}"

- name:               Clean temporary files.
  file:
    path:             "{{ download }}/{{ item.file }}"
    state:            absent
  delegate_to:        "{{ groups['masters'][0] }}"
  run_once:           true
  with_items:
  - "{{ packages.cfssl }}"
  - "{{ packages.cfssljson }}"


- name:               "Symlinks CA tools."
  file:
    src:              "{{ opt }}/{{ item.1.name }}"
    dest:             "{{ bin }}/{{ item.1.name }}"
    state:            link
    force:            yes
  delegate_to:        "{{ groups['masters'][0] }}"
  run_once:           true
  with_indexed_items:
  - "{{ packages.cfssl }}"
  - "{{ packages.cfssljson }}"
