---
- name:               Determine if tools exist.
  stat:
    path:             "{{ download }}/{{ item.file }}"
  register:           tmp_ca_tool
  delegate_to:        "{{ groups['masters'][0] }}"
  run_once:           true
  with_items:
  - "{{ packages.cfssl }}"
  - "{{ packages.cfssljson }}"

- name:               Download CA tools.
  get_url:
    url:              "{{ item.1.url }}/{{ item.1.file }}"
    dest:             "{{ download }}/{{ item.1.file }}"
  when:               "{{ not tmp_ca_tool.results[item.0].stat.exists }}"
  delegate_to:        "{{ groups['masters'][0] }}"
  run_once:           true
  with_indexed_items:
  - "{{ packages.cfssl }}"
  - "{{ packages.cfssljson }}"
  register:           ca_tool_down

- name:               Determine if CA tools in current directory.
  stat:
    path:             "{{ item.dir }}"
  register:           ca_tool_current_dir
  delegate_to:        "{{ groups['masters'][0] }}"
  run_once:           true
  with_items:
  - "{{ packages.cfssl }}"
  - "{{ packages.cfssljson }}"

- name:               copy CA tools to current directory.
  when:               "{{ not ca_tool_current_dir.results[item.0].stat.exists }}"
  copy:
    src:              "{{ download }}/{{  item.1.file }}"
    dest:             "{{ item.1.dir }}"
    owner:            root
    group:            root
    mode:             0755
    remote_src:       True
  register:           ca_tool
  delegate_to:        "{{ groups['masters'][0] }}"
  run_once:           true
  with_indexed_items:
  - "{{ packages.cfssl }}"
  - "{{ packages.cfssljson }}"

- name:               Determine if Symlinks CA tools exist.
  stat:
    path:             "{{ bin }}/{{ item.name }}"
  register:           symlinks_ca_tool
  delegate_to:        "{{ groups['masters'][0] }}"
  run_once:           true
  with_items:
  - "{{ packages.cfssl }}"
  - "{{ packages.cfssljson }}"

- name:               "Symlinks CA tools."
  file:
    src:              "{{ item.1.dir }}"
    dest:             "{{ bin }}/{{ item.1.name }}"
    state:            link
    force:            yes
  when:               "{{ not symlinks_ca_tool.results[item.0].stat.exists and ca_tool}} "
  delegate_to:        "{{ groups['masters'][0] }}"
  run_once:           true
  with_indexed_items:
  - "{{ packages.cfssl }}"
  - "{{ packages.cfssljson }}"
