---

- name:               Determine if client certificate config exist
  stat:
    path:             "{{ path }}/{{ item }}/{{ item }}-{{ client_csr }}"
  with_items:
    - "{{ kubernetes.certification }}"
  delegate_to:        "{{ groups['masters'][0] }}"
  run_once:           true
  register:           client_csr_path

- name:               If not, then set up client certificate config
  when:               not  client_csr_path.results[item.0].stat.exists
  template:
    src:              ca-csr.json.j2
    dest:              "{{ path }}/{{ item.1 }}/{{ item.1 }}-{{ client_csr }}"
    mode:             '0600'
  with_indexed_items:
    - "{{ kubernetes.certification }}"
  delegate_to:        "{{ groups['masters'][0] }}"
  run_once:           true
